// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4efCjn89pbu4eElLFa3E8H7FC0w4qY-w',
    appId: '1:6231951620:web:b08e175e71b8adcb31e851',
    messagingSenderId: '6231951620',
    projectId: 'holidayrate',
    authDomain: 'holidayrate.firebaseapp.com',
    storageBucket: 'holidayrate.appspot.com',
    measurementId: 'G-J1K5BZ3WS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcBeuz0Gg7a4RFRP4_YTQAf4i1jodb0cs',
    appId: '1:6231951620:android:77980c9d27fe409731e851',
    messagingSenderId: '6231951620',
    projectId: 'holidayrate',
    storageBucket: 'holidayrate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChmTtnNbOMKV381TfleUUlHnAwLSO_eCo',
    appId: '1:6231951620:ios:0e0a5929440fffb831e851',
    messagingSenderId: '6231951620',
    projectId: 'holidayrate',
    storageBucket: 'holidayrate.appspot.com',
    androidClientId: '6231951620-hgi5u7c8g1657hp48bck53rcv4qhk8ps.apps.googleusercontent.com',
    iosClientId: '6231951620-2a5g1qtask91sue752ovja686p6eqd8d.apps.googleusercontent.com',
    iosBundleId: 'com.devulopa.averageHolidayRatePay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChmTtnNbOMKV381TfleUUlHnAwLSO_eCo',
    appId: '1:6231951620:ios:0c4ba97c4653472c31e851',
    messagingSenderId: '6231951620',
    projectId: 'holidayrate',
    storageBucket: 'holidayrate.appspot.com',
    androidClientId: '6231951620-hgi5u7c8g1657hp48bck53rcv4qhk8ps.apps.googleusercontent.com',
    iosClientId: '6231951620-8484sf7ed6d4nf1hk0d4d8ecac1jpphn.apps.googleusercontent.com',
    iosBundleId: 'com.devulopa.averageHolidayRatePay.RunnerTests',
  );
}
